### PR TITLE
Added Theme by to the footer of the Docs

### PR DESCRIPTION
**Pull request by m-aditya**
For #19

### CODE REVIEW

**Comment by mohammedzamakhan** [comment]
I don't see any logic for not showing this for mobile layout

**Comment by mohammedzamakhan** [comment]
Can you please make sure that, the theme statement doesn't show up on mobile layout. Thx

**Comment by m-aditya** [comment]
Fixed that

**Comment by mohammedzamakhan** [comment]
Thanks @m-aditya

**Comment by mohammedzamakhan** [comment]
Will add you as a contributor in the next release

**Pull request merged**
